### ISSUE TITLE
Template helper to replace the experimental WriteFile helper

### ISSUE THREAD

**Issue by phodge** [phodge/homely#30]
Create a `template()` decorator that's easier to use than WriteFile and won't accidentally deleted
a file after it's changed by the user

**Comment by tlamadon** [comment]
Hi, is there any development on this? Or is there a recommended way to change the content of a managed file from python? I tried to use `blockinfile` but that doesn't seem to work if applied on one of the managed files. Maybe I did something wrong.

I have noticed that you use writefile in your own config.

Also, let say that you have nailed it here! This is just the best way to manage dotfiles, period! Thanks for the work!

**Comment by phodge** [comment]
@tlamadon: thank you for the kind words! I have made `writefile()` part of the official API in version 0.19.0 just now, you can read the docs on it here: https://homely.readthedocs.io/en/latest/ref/files.html#homely-files-writefile.

**Comment by phodge** [comment]
I'm probably not going to go ahead with a `template()` helper after all, since the lack of automatic cleanup would mean it is really just equivalent to:

    if not os.path.exists(template_path):
        with open(template_path, 'w') as f:
            f.write(...)
