### ISSUE TITLE
"Not a git repository" error

### ISSUE THREAD

**Issue by daks** [phodge/homely#47]
Hello,

I'm evaluating homely to manage my dotfiles. I installed it on my Debian Jessie box, using Python 2.7.13. Homely was installed using `pip install homely --user` command.

Following documentation, I tried to add a repository with the following _(obfuscated)_ command

```
homely add ssh://git@srv.domain.tld/dotfiles
ERROR: Not a git repository: ssh://git@srv.domain.tld/dotfiles
```

Of course, the repository URL is a correct one, and I can
```
git clone ssh://git@peter.sietch-tabr.com/dotfiles
Cloning into 'dotfiles'...
warning: You appear to have cloned an empty repository.
```

**Comment by phodge** [comment]
Hi! I haven't had a chance to check the code just yet, but I suspect I naively added a regex filter to the `homely add` command that's not allowing `ssh://` repo URLs. A temporary workaround would be to `git clone ssh://your.domain/dotfiles ~/dotfiles` and then `homely add ~/dotfiles`.

You can also leave this ticket open and I'll remove this unnecessary error when I get a chance.

P.S. sorry for the late reply - I've been away on holidays.
