### ISSUE TITLE
general.include() to return the loaded module

### ISSUE THREAD

**Issue by tlamadon** [phodge/homely#54]
Maybe I am not using `homely.general.include`, but I would find convenient if it returned the loaded module. I would like to be able to access some of the local variables defined in include.

As a work around, I have noticed that you import it with the prefix `__imported_by_homely_`, and I get then get it from the `sys` module, but I need to keep track of the order in which they are loaded.

Thanks, great project!

**Comment by phodge** [comment]
Hi @tlamadon, I've added `homely.general.include()` as a publicly available feature in version 0.20.0. You can read the docs [here](https://homely.readthedocs.io/en/latest/ref/general.html).
